CONFIG = {
    'FACEBOOK_TOKEN': 'EAACURkd8Ul0BAAUzb2SVz3s6YBZAdTSurSup9ZCpJjdZB7WZBvf5bGutblN3qrDxl1KJUXQTlccALVPOyRkQYoJ6JuFGCJriXZCZBsZCwy2XEdvUZCH8ZCz54jgNKZAYHmHajIkGear9a5cioJ71xhxvryZCkNENLDquZBsRBAfJZAbWtfPq9WWPKYw2u',
    'VERIFY_TOKEN': '1234567890',
    'SERVER_URL': 'https://fbchatbotuni.herokuapp.com/'
}